class Config:
    SQLALCHEMY_DATABASE_URI = 'sqlite:///data.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = 'SECRETKEY'
    JWT_SECRET_KEY = 'JWTSECRETKEY'
    WTF_CSRF_ENABLED = True

